# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
data = np.loadtxt('data\minutes_n_ingredients.csv', delimiter=',', dtype=np.int32, skiprows=1)
data[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
data[:, 1:].mean(axis=0)

array([2.16010017e+04, 9.05528000e+00])

In [3]:
data[:, 1:].min(axis=0)

array([0, 1])

In [4]:
data[:, 1:].max(axis=0)

array([2147483647,         39])

In [5]:
np.median(data[:, 1:], axis=0)

array([40.,  9.])

3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [6]:
time = data[:, 1]
np.quantile(time, 0.75)

65.0

In [7]:
data[:, 1] = np.clip(time, None, np.quantile(time, 0.75))
data[:20, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14],
       [152828,     40,      7],
       [ 33941,     18,      9],
       [446597,     15,      5],
       [366174,      7,      9],
       [ 74205,     20,      7],
       [504666,     65,     20],
       [ 81006,     12,      7],
       [280968,     65,     11],
       [204134,      5,      3],
       [ 18593,     35,      7],
       [ 25623,      6,      4],
       [ 65559,     24,     14],
       [ 99836,     65,      7],
       [ 87775,     65,     13],
       [425704,     40,     12]])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [8]:
# time.size - np.count_nonzero(time)
time[time == 0].size

479

In [9]:
time[time == 0] = 1
data[-20:,:]

array([[420725,      5,      3],
       [220747,     65,      8],
       [273128,     25,     17],
       [147074,     65,     15],
       [382708,     25,     13],
       [  4747,      1,      9],
       [351058,     40,      4],
       [ 44120,     17,      5],
       [138453,     30,      7],
       [227056,     30,      4],
       [ 60756,     15,      5],
       [ 52088,     60,      5],
       [128811,     15,      4],
       [360109,     30,     10],
       [371794,     35,      8],
       [ 43407,     35,      7],
       [287943,     65,     15],
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,     65,     14]])

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [10]:
np.unique(data[:, 0]).size

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [11]:
np.unique(data[:, 2]).size

37

In [12]:
np.unique(data[:, 2])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 37, 39])

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [13]:
data_2 = data[data[:, 2] <= 5]
len(data_2)

17262

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [14]:
a = data[:, 2]/data[:, 1]
max(a)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [15]:
data_sorted = data[data[:, 1].argsort()[::-1]][:100, :]
np.mean(data_sorted, axis=0)[2]

9.96

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [16]:
a = np.random.randint(0, len(data), 10)
# a = np.random.choice(len(data), 10, replace=False)
# a = np.random.permutation(np.arange(len(data)))[:10]
data[a, :]

array([[195921,     65,      4],
       [173179,     50,      9],
       [459532,     50,     11],
       [181477,     65,     12],
       [  7104,      1,      4],
       [ 15671,     65,      9],
       [ 92880,     20,      4],
       [ 19640,     22,      7],
       [358500,     65,     16],
       [   232,     54,     11]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [17]:
average = np.mean(data[:, 2])
average

9.05528

In [18]:
len(data[data[:, 2] < average])*100/len(data)

58.802

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [19]:
is_simple = (data[:, 1] <= 20) & (data[:, 2] <= 5) 
data_3 = np.append(data, is_simple[:, np.newaxis], axis=1)
data_3

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [20]:
len(data_3[data_3[:, 3] == 1])
len(data_3[data_3[:, 3] == 1])*100/len(data_3)

9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [21]:
a = data[data[:, 1] < 10]
len(a)

7588

In [22]:
b = data[(10 < data[:, 1]) & (data[:,1] < 20)]
len(b)

7783

In [23]:
c = data[20 <= data[:, 1]]
len(c)

79751

In [24]:
min_len = min(len(a), len(b), len(c)) 
min_len

7588

In [25]:
a, b, c = a[:min_len, :], b[:min_len, :], c[:min_len, :]
arr = np.stack((a, b, c)) 
arr.shape

(3, 7588, 3)